---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - z0r1k
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - z0r1k
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - z0r1k
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # - package-ecosystem: "terraform"
  #   directory: "/"
  #   schedule:
  #     interval: weekly
  #   assignees:
  #     - z0r1k
  #   reviewers:
  #     - z0r1k
  #   labels:
  #     - dependencies
  #   commit-message:
  #     prefix: "chore"
  #     include: scope
  #   groups:
  #     dependencies:
  #       applies-to: version-updates
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"
  #         - "patch"
